version: 2.1

orbs:
  slack: circleci/slack@4.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: bhogayatajay/portfio
    docker:
      - image: circleci/node
 
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - slack/notify:
          event: fail
          mentions: '@jaybhogayata53'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:latest
      - slack/notify:
          event: fail
          mentions: '@jaybhogayata53'
          template: basic_fail_1
          color: "#00FF00"
          message: A Docker image is pushed to dockerhub
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          color: "#FF0000"
          message: A Docker image fail pushed to dockerhub

      
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main



      
