version: 2.1

orbs:
  slack: circleci/slack@4.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: bhogayatajay/portfio
    docker:
      - image: circleci/node

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - slack/notify:
          event: fail
          mentions: "@jaybhogayata53"
          template: basic_fail_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "A container build fail",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "A container is build successfuly.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:latest
      - slack/notify:
          event: fail
          mentions: "@jaybhogayata53"
          template: basic_fail_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "A container fail to push to hub",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "A container pushed to hub",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
  deploy:
    working_directory: /app
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli

      - run:
          name: Deploying
          command: eb deploy Myportfoio-env

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main

      - deploy:
          requires:
            - publish-latest
          filters:
            branches:
              only: main
